---
title: "Managing Python Environments"
subtitle: "Why it's important and how to do it"
format:
  revealjs:
    theme: default
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    css: styles.css
    footer: 'Python Environment Guide'
---

## Why Use Python Environments?

-   ***Dependency Isolation***: Different projects often require different package versions

-   ***Reproducibility***: Ensures code works the same way across different operating systems

-   ***Conflict Prevention***: Avoids "dependency hell" where package requirements clash

## Important Terms

| Tool      | Description                                                                                                                        |
|---------------|--------------------------------------------------------------|
| **Pip**   | \- Python package manager<br>- Simpler dependency solver<br>- Uses `requirements.txt` for dependencies                             |
| **Conda** | \- Package **and** environment manager<br>- *Complex* dependency solver (= fewer conflicts)<br>- Uses YAML-based environment files |
| **Mamba** | \- She's Conda, but better and faster                                                                                              |

## Other terms you might hear

-   **Miniconda** = lightweight version of conda that avoids installing the full Anaconda distribution

-   **Micromamba** = lightweight version of mamba that's useful for testing in containers

## Best practices

1.  Avoid installing additional packages into your Base environment.

2.  Every python project should have its own environment.

3.  Environments should only contain the packages you need.

4.  Keep track of all of your packages in an text or yml file and include it in your github repositories.

## Setup

-   Install [Anaconda](https://ucsb-meds.github.io/MEDS-installation-guide/#install-Anaconda)

-   ***Note***: when prompted in the installation process, you should add conda to your system path so that it will recognize conda as a command. If you miss this step, you can still do it. Just ask your preferred GenAI how to add conda to your system path.

## Let's create the mamba-env you'll use to install other environments

First, we'll create a conda environment from scratch that just contains mamba. You'll use this environment to install your other conda environments faster.

``` python
# Create environment
conda create -n mamba-env

# List all conda environments and locations to confirm it was created
conda env list

# Activate your environment 
conda activate mamba-env

# Install mamba
conda install mamba -c conda-forge

# Deactivate your environment when you don't need it
conda deactivate
```

## Create environments from an environment.yml file

Example environment.yml file [here](https://github.com/katleyq/python-env-guide/blob/main/example-environment/environment.yml).

``` python
# Activate your mamba-env used for installing environments
conda activate mamba-env

# Navigate to the directory with the .yml file
cd /path/to/yml

# Create your environment from the .yml
mamba create -f environment.yml

# Deactivate your mamba-env now that you're done installing
conda deactivate

# Activate your new environment
conda activate example-environment
```

## Create environments from scratch 

You can also just create a bare environment, and install packages 1 by 1.

``` python
# Create your environment with python3.8 and mamba
conda create --name example_environment python=3.8 mamba

# Activate your new environment
conda activate example_environment

# Install whatever packages you need (ex: numpy and xarray)
mamba install numpy xarray

# You can also install specific versions if needed
mamba install pandas=1.3.3

# Deactivate when not in use
conda deactivate
```

## Summary

-   Use python environments! This will save you a lot of time.

-   Don't install additional packages in your base environment.

-   Create an environment for each Python project.

-   Use mamba for faster installation.
